
#    url: jdbc:postgresql://127.0.0.1:5432/demo_replica_ds_0?serverTimezone=UTC&useSSL=false
#  replica_ds_1:
#    url: jdbc:postgresql://127.0.0.1:5432/demo_replica_ds_1?serverTimezone=UTC&useSSL=false
#
#rules:
#- !REPLICA_QUERY
#  dataSources:
#    pr_ds:
#      name: pr_ds
#      primaryDataSourceName: primary_ds
#      replicaDataSourceNames:
#        - replica_ds_0
#        - replica_ds_1

######################################################################################################
#
# If you want to connect to MySQL, you should manually copy MySQL driver to lib directory.
#
######################################################################################################

schemaName: replica_query_db
#
#dataSourceCommon:
#  username: root
#  password: 12345678
#  connectionTimeoutMilliseconds: 30000
#  idleTimeoutMilliseconds: 60000
#  maxLifetimeMilliseconds: 1800000
#  maxPoolSize: 50
#  minPoolSize: 1
#  maintenanceIntervalMilliseconds: 30000
#
dataSources:
  primary_ds:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false
    username: root
    password: 150405
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    maintenanceIntervalMilliseconds: 30000
  replica_ds_0:
    url: jdbc:mysql://localhost:3306/test_bak?serverTimezone=UTC&useSSL=false
    username: root
    password: 150405
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    maintenanceIntervalMilliseconds: 30000
  replica_ds_1:
    url: jdbc:mysql://localhost:3306/test_bak2?serverTimezone=UTC&useSSL=false
    username: root
    password: 150405
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    maintenanceIntervalMilliseconds: 30000
#
rules:
  - !REPLICA_QUERY
    dataSources:
      pr_ds:
        name: pr_ds
        primaryDataSourceName: primary_ds
        replicaDataSourceNames:
          - replica_ds_0
          - replica_ds_1