server:
  port: 8089

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/replica_query_db?useServerPrepStmts=true&cachePrepStmts=true
    username: root
    password: 150405

#mybaits配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
